In [4]:
import pandas as pd
import numpy as np
import json

In [5]:
bicimad_stations=pd.read_csv("../data/raw/bicimad_stations.csv").drop_duplicates()
instalaciones=pd.read_csv("../data/raw/instalaciones_deportivas_madrid.csv", sep=";").drop_duplicates()

In [6]:
instalaciones.head()

,PK,NOMBRE,DESCRIPCION-ENTIDAD,HORARIO,EQUIPAMIENTO,TRANSPORTE,DESCRIPCION,ACCESIBILIDAD,CONTENT-URL,NOMBRE-VIA,...,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TELEFONO,FAX,EMAIL,TIPO,Unnamed: 30
0,11353987,Instalación Deportiva Básica Embalse de San Juan,NaN,NaN,Pista de baloncesto. Pista de fútbol sala.,"Bus: 58 , 63 , 145Renfe: Santa Eugenia",NaN,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,EMBALSE DE SAN JUAN,...,VILLA DE VALLECAS,449213.0,4468179.0,40.362643,-3.598148,NaN,NaN,NaN,/contenido/entidadesYorganismos/CentrosEspacio...,
1,6344681,Instalación Deportiva Básica Alto del Retiro,NaN,NaN,Pista polideportiva (marcajes de fútbol sala y...,Metro: Las Suertes,NaN,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,ALTO DEL RETIRO,...,VILLA DE VALLECAS,450057.0,4468715.0,40.367515,-3.588265,NaN,NaN,NaN,/contenido/entidadesYorganismos/CentrosEspacio...,
2,11350944,Instalación Deportiva Básica Avenida de Cerro ...,NaN,NaN,Pista de minibaloncesto. Pista de minifútbol,Metro: CongostoBus: 142,NaN,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,CERRO MILANO,...,VILLA DE VALLECAS,447502.0,4468855.0,40.368619,-3.618357,NaN,NaN,NaN,/contenido/entidadesYorganismos/CentrosEspacio...,
3,11350990,Instalación Deportiva Básica Avenida de las Su...,NaN,NaN,Pista de baloncesto. Pista polideportiva (marc...,Metro: Las Suertes,NaN,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,avenida de las Suertes,...,VILLA DE VALLECAS,448037.0,4469037.0,40.370297,-3.612067,NaN,NaN,NaN,/contenido/entidadesYorganismos/CentrosEspacio...,
4,11350948,Instalación Deportiva Básica Avenida del Ensan...,NaN,NaN,Pista de minibaloncesto. Pista de minifútbol. ...,Metro: Las Suertes,NaN,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,ENSANCHE DE VALLECAS,...,VILLA DE VALLECAS,448037.0,4469037.0,40.370297,-3.612067,NaN,NaN,NaN,/contenido/entidadesYorganismos/CentrosEspacio...,

In [7]:
bicimad_stations.head()

,id,name,light,number,address,activate,no_available,total_bases,dock_bikes,free_bases,reservations_count,geometry_type,geometry_coordinates
0,1,Puerta del Sol A,2,1a,Puerta del Sol nº 1,1,0,30,15,11,0,Point,"[-3.7018341, 40.4172137]"
1,2,Puerta del Sol B,1,1b,Puerta del Sol nº 1,1,0,30,22,4,0,Point,"[-3.701602938060457, 40.41731271011562]"
2,3,Miguel Moya,2,2,Calle Miguel Moya nº 1,1,0,24,12,11,0,Point,"[-3.7058415, 40.4205886]"
3,4,Plaza Conde Suchil,0,3,Plaza del Conde del Valle de Súchil nº 3,1,0,18,4,11,0,Point,"[-3.7069171, 40.4302937]"
4,5,Malasaña,2,4,Calle Manuela Malasaña nº 5,1,0,24,12,12,0,Point,"[-3.7025875, 40.4285524]"

In [8]:
coordinates_stations = [i.split(",") for i in bicimad_stations["geometry_coordinates"]]
longitud = [float(j[0].replace("[","").strip()) for j in coordinates_stations]
latitud = [float(j[1].replace("]","").strip()) for j in coordinates_stations]
bicimad_stations["latitude"]=latitud
bicimad_stations["longitude"]=longitud

bicimad_stations["latitude"]=pd.to_numeric(bicimad_stations["latitude"])
bicimad_stations["longitude"]=pd.to_numeric(bicimad_stations["longitude"])

bicimad_stations

,id,name,light,number,address,activate,no_available,total_bases,dock_bikes,free_bases,reservations_count,geometry_type,geometry_coordinates,latitude,longitude
0,1,Puerta del Sol A,2,1a,Puerta del Sol nº 1,1,0,30,15,11,0,Point,"[-3.7018341, 40.4172137]",40.417214,-3.701834
1,2,Puerta del Sol B,1,1b,Puerta del Sol nº 1,1,0,30,22,4,0,Point,"[-3.701602938060457, 40.41731271011562]",40.417313,-3.701603
2,3,Miguel Moya,2,2,Calle Miguel Moya nº 1,1,0,24,12,11,0,Point,"[-3.7058415, 40.4205886]",40.420589,-3.705842
3,4,Plaza Conde Suchil,0,3,Plaza del Conde del Valle de Súchil nº 3,1,0,18,4,11,0,Point,"[-3.7069171, 40.4302937]",40.430294,-3.706917
4,5,Malasaña,2,4,Calle Manuela Malasaña nº 5,1,0,24,12,12,0,Point,"[-3.7025875, 40.4285524]",40.428552,-3.702587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,266,Ciudad Universitaria 1,0,258,Avenida de la Complutense (Metro Ciudad Univer...,1,0,24,0,24,0,Point,"[-3.72699, 40.44375]",40.443750,-3.726990
260,267,Ciudad Universitaria 2,2,259,Avenida de la Complutense (Metro Ciudad Univer...,1,0,24,12,12,0,Point,"[-3.72693, 40.44342]",40.443420,-3.726930
261,268,Facultad Biología,2,260,Calle José Antonio Novais frente al nº 12,1,0,24,9,14,0,Point,"[-3.7272945, 40.4483322]",40.448332,-3.727295
262,269,Facultad Derecho,0,261,Avenida Complutense nº 23,1,0,24,5,18,0,Point,"[-3.72937, 40.45109]",40.451090,-3.729370
263,270,Zurbano,0,247,Calle Zurbano nº 90,1,0,24,6,15,0,Point,"[-3.69281, 40.43837]",40.438370,-3.692810

In [9]:
from shapely.geometry import Point
import geopandas as gpd   # conda install -c conda-forge geopandas

def to_mercator(lat, long):
    # transform latitude/longitude data in degrees to pseudo-mercator coordinates in metres
    c = gpd.GeoSeries([Point(lat, long)], crs=4326)
    c = c.to_crs(3857)
    return c

def distance_meters(lat_start, long_start, lat_finish, long_finish):
    # return the distance in metres between to latitude/longitude pair point in degrees (i.e.: 40.392436 / -3.6994487)
    start = to_mercator(lat_start, long_start)
    finish = to_mercator(lat_finish, long_finish)
    return start.distance(finish)

In [10]:
nearest_distance=pd.DataFrame(columns=["ins_latitude","ins_longitude","bicimad_latitude","bicimad_longitude","distance","name_station","address_station","id"])

for i in instalaciones.index:
    a=(float(instalaciones["LATITUD"][i]))
    b=(float(instalaciones["LONGITUD"][i]))

    distance=pd.DataFrame(columns=["distance","latitude","longitude"])

    for j in bicimad_stations.index:
        c=(float(bicimad_stations["latitude"][j]))
        d=(float(bicimad_stations["longitude"][j]))
        name=bicimad_stations["name"][j]
        address=bicimad_stations["address"][j]
        id_station=bicimad_stations["id"][j]
        e=distance_meters(a, b, c, d)

        distance=distance.append({"distance":e[0],"latitude":c,"longitude":d,"name":name,"address":address,"id":id_station},ignore_index=True)
    
    nearest_station=distance.iloc[distance["distance"].idxmin()]
    nearest_distance=nearest_distance.append({"ins_latitude":a,"ins_longitude":b,"bicimad_latitude":nearest_station[1],"bicimad_longitude":nearest_station[2],"distance":nearest_station[0],"name_station":nearest_station[3],"address_station":nearest_station[4],"id":nearest_station[5]},ignore_index=True)

In [3]:
nearest_distance

NameError: name 'nearest_distance' is not defined

In [23]:
nearest_distance.to_csv("../data/processed/nearest_stations.csv", index=False)