In [6]:
import pandas as pd
import numpy as np
import json

In [7]:
bicimad_stations=pd.read_csv("../data/raw/bicimad_stations.csv").drop_duplicates()
instalaciones=pd.read_csv("../data/raw/instalaciones_deportivas_madrid.csv", sep=";").drop_duplicates()

In [8]:
bicimad_stations.head()

,id,name,light,number,address,activate,no_available,total_bases,dock_bikes,free_bases,reservations_count,geometry_type,geometry_coordinates
0,1,Puerta del Sol A,2,1a,Puerta del Sol nº 1,1,0,30,15,11,0,Point,"[-3.7018341, 40.4172137]"
1,2,Puerta del Sol B,1,1b,Puerta del Sol nº 1,1,0,30,22,4,0,Point,"[-3.701602938060457, 40.41731271011562]"
2,3,Miguel Moya,2,2,Calle Miguel Moya nº 1,1,0,24,12,11,0,Point,"[-3.7058415, 40.4205886]"
3,4,Plaza Conde Suchil,0,3,Plaza del Conde del Valle de Súchil nº 3,1,0,18,4,11,0,Point,"[-3.7069171, 40.4302937]"
4,5,Malasaña,2,4,Calle Manuela Malasaña nº 5,1,0,24,12,12,0,Point,"[-3.7025875, 40.4285524]"

In [9]:
instalaciones.head()

,PK,NOMBRE,DESCRIPCION-ENTIDAD,HORARIO,EQUIPAMIENTO,TRANSPORTE,DESCRIPCION,ACCESIBILIDAD,CONTENT-URL,NOMBRE-VIA,...,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TELEFONO,FAX,EMAIL,TIPO,Unnamed: 30
0,11353987,Instalación Deportiva Básica Embalse de San Juan,NaN,NaN,Pista de baloncesto. Pista de fútbol sala.,"Bus: 58 , 63 , 145Renfe: Santa Eugenia",NaN,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,EMBALSE DE SAN JUAN,...,VILLA DE VALLECAS,449213.0,4468179.0,40.362643,-3.598148,NaN,NaN,NaN,/contenido/entidadesYorganismos/CentrosEspacio...,
1,6344681,Instalación Deportiva Básica Alto del Retiro,NaN,NaN,Pista polideportiva (marcajes de fútbol sala y...,Metro: Las Suertes,NaN,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,ALTO DEL RETIRO,...,VILLA DE VALLECAS,450057.0,4468715.0,40.367515,-3.588265,NaN,NaN,NaN,/contenido/entidadesYorganismos/CentrosEspacio...,
2,11350944,Instalación Deportiva Básica Avenida de Cerro ...,NaN,NaN,Pista de minibaloncesto. Pista de minifútbol,Metro: CongostoBus: 142,NaN,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,CERRO MILANO,...,VILLA DE VALLECAS,447502.0,4468855.0,40.368619,-3.618357,NaN,NaN,NaN,/contenido/entidadesYorganismos/CentrosEspacio...,
3,11350990,Instalación Deportiva Básica Avenida de las Su...,NaN,NaN,Pista de baloncesto. Pista polideportiva (marc...,Metro: Las Suertes,NaN,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,avenida de las Suertes,...,VILLA DE VALLECAS,448037.0,4469037.0,40.370297,-3.612067,NaN,NaN,NaN,/contenido/entidadesYorganismos/CentrosEspacio...,
4,11350948,Instalación Deportiva Básica Avenida del Ensan...,NaN,NaN,Pista de minibaloncesto. Pista de minifútbol. ...,Metro: Las Suertes,NaN,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,ENSANCHE DE VALLECAS,...,VILLA DE VALLECAS,448037.0,4469037.0,40.370297,-3.612067,NaN,NaN,NaN,/contenido/entidadesYorganismos/CentrosEspacio...,

In [10]:
coordinates_stations = [i.split(",") for i in bicimad_stations["geometry_coordinates"]]
longitud = [float(j[0].replace("[","").strip()) for j in coordinates_stations]
latitud = [float(j[1].replace("]","").strip()) for j in coordinates_stations]
bicimad_stations["latitude"]=latitud
bicimad_stations["longitude"]=longitud

bicimad_stations["latitude"]= pd.to_numeric(bicimad_stations["latitude"])
bicimad_stations["longitude"]= pd.to_numeric(bicimad_stations["longitude"])
bicimad_stations.head()

,id,name,light,number,address,activate,no_available,total_bases,dock_bikes,free_bases,reservations_count,geometry_type,geometry_coordinates,latitude,longitude
0,1,Puerta del Sol A,2,1a,Puerta del Sol nº 1,1,0,30,15,11,0,Point,"[-3.7018341, 40.4172137]",40.417214,-3.701834
1,2,Puerta del Sol B,1,1b,Puerta del Sol nº 1,1,0,30,22,4,0,Point,"[-3.701602938060457, 40.41731271011562]",40.417313,-3.701603
2,3,Miguel Moya,2,2,Calle Miguel Moya nº 1,1,0,24,12,11,0,Point,"[-3.7058415, 40.4205886]",40.420589,-3.705842
3,4,Plaza Conde Suchil,0,3,Plaza del Conde del Valle de Súchil nº 3,1,0,18,4,11,0,Point,"[-3.7069171, 40.4302937]",40.430294,-3.706917
4,5,Malasaña,2,4,Calle Manuela Malasaña nº 5,1,0,24,12,12,0,Point,"[-3.7025875, 40.4285524]",40.428552,-3.702587

In [23]:
from shapely.geometry import Point
import geopandas as gpd   # conda install -c conda-forge geopandas

def to_mercator(lat, long):
    # transform latitude/longitude data in degrees to pseudo-mercator coordinates in metres
    c = gpd.GeoSeries([Point(lat, long)], crs=4326)
    c = c.to_crs(3857)
    return c

def distance_meters(lat_start, long_start, lat_finish, long_finish):
    # return the distance in metres between to latitude/longitude pair point in degrees (i.e.: 40.392436 / -3.6994487)
    start = to_mercator(lat_start, long_start)
    finish = to_mercator(lat_finish, long_finish)
    return start.distance(finish)

In [28]:
a= distance_meters(bicimad_stations["latitude"][0], bicimad_stations["longitude"][0], 40.4172137, -3.7016)
a

0    26.114376
dtype: float64